name: Production Build
on:
     # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:    
jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.0.0]
        
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Yarn Install
      run: |
        yarn install
    - name: Development Build
      run: |
        yarn build
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        AWS_S3_BUCKET: ${{ secrets.AWS_PROD_BUCKET_NAME }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  
        SOURCE_DIR: "build"
    - name: Deploy static site to S3 bucket
      run: |
        aws sync . s3://sprykerfrontend          
